services:
  elasticsearch:
    image: bitnami/elasticsearch:8
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: bitnami/kibana:8
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  logstash:
    image: bitnami/logstash:8
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/opt/bitnami/logstash/pipeline/logstash.conf
